### ISSUE TITLE
Prikaz regij

### ISSUE THREAD

**Issue by evaozebek** [evaozebek/APPR-2017-18#2]
Pri izrisovanju zemljevida mi ne kaže štirih regij:
<img width="623" alt="screen shot 2018-01-11 at 16 01 12" src="https://user-images.githubusercontent.com/28061924/34832368-0c29b0f4-f6ea-11e7-9dd7-8af37a100e31.png">

Regije v zemljevidu so označene tako, a mi nekaterih sploh ne kaže in piše NA
<img width="604" alt="screen shot 2018-01-11 at 16 06 42" src="https://user-images.githubusercontent.com/28061924/34832381-179404bc-f6ea-11e7-9bbc-68e694bc6969.png">

Regije v moji tabeli pa izgledajo tako:
<img width="132" alt="screen shot 2018-01-11 at 16 06 09" src="https://user-images.githubusercontent.com/28061924/34832397-21b47b66-f6ea-11e7-9595-91f7038aa70c.png">

Poskušala sem zamenjavo opraviti kar v zemljevidu, a je problem, saj nekaterih regij v zemljevidu sploh ne kaže, izgleda kot da je v zemljevidu zajetih samo 7 regij, v mojih podatkih pa 12. 
Hvala za pomoč

**Comment by jaanos** [comment]
Problem se pojavi pri pretvarjanju imen regij s šumniki - iz nekega razloga na Macu to ne deluje pravilno, in se ta imena nadomestijo z `NA`. Lahko poskusiš pri funkciji `uvozi.zemljevid` podati parameter `encoding = ""` (torej prazen niz) - potem poglej, ali imaš v zemljevidu vsa imena regij. Če so in se pojavljajo čudni znaki, jih lahko potem nadomestiš (za iskanje lahko uporabiš funkcijo `grep`, s katero lahko iščeš po vzorcih - v tvojem primeru torej po delih nizov brez šumnikov). Če to ne bi šlo, lahko poskusiš s parametrom `encoding = "UTF-8//TRANSLIT"` - ta ti bo morda celo odstranil strešice, a je to lahko le začasna rešitev, saj se pretvorba na vseh sistemih ne bo obnašala enako (pri meni npr. deluje enako kot `UTF-8`).

Ena [možnost](http://www.janosgyerik.com/fixing-r-error-in-mac-os-x-tar-failed-to-set-default-locale/), ki jo lahko še poskusiš: ugasni RStudio, nato pa v terminalu izvedi sledeči ukaz:
```sh
defaults write org.R-project.R force.LANG en_US.UTF-8
```
Potem znova prižgi RStudio in preveri, ali delujejo šumniki.

**Comment by evaozebek** [comment]
Pomagalo je že, da sem encoding spremenila v "", tako da zdaj prikaz deluje za vse regije, razen za Obalno-kraško. Čeprav sem spremenila, tako kot pri ostalih regijah, iz Obalno-kraške v Obalno-krasko, pri tej regiji to ne deluje, pa ne vem zakaj. 

`levels(zemljevid$NAME_1)[levels(zemljevid$NAME_1) %in%
                           c("Notranjsko-kraška",
                             "Spodnjeposavska", "Koroška", "Goriška", "Obalno-kraška ")] <- c("Primorsko-notranjska",
                                                      "Posavska", "Koroska", "Goriska", "Obalno-kraska")`

**Comment by jaanos** [comment]
Za `Obalno-kraška` imaš presledek - odstrani ga, pa bo delovalo.
